# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

services:
- docker

env:
- CACHE_DIR=docker_image

# Add a simple cache for docker images as explained here
# https://stackoverflow.com/questions/32866599/can-travis-ci-cache-docker-images/41975912
cache:
  directories:
  - ${CACHE_DIR}

before_cache:
- make cache_dir=${CACHE_DIR} save

jobs:
  include:

    - stage: build
      script: make build

    - stage: test
      before_install:
      - make cache_dir=${CACHE_DIR} load
      script: make test

    - stage: deploy
      before_install:
      - make cache_dir=${CACHE_DIR} load
      script: make deploy

