# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

services:
- docker

script:
# Create the docker image
- docker build -t jecaro/hscalendar-server .
# Test the created image
- docker run -t jecaro/hscalendar-server ./hscalendar-test

# Deploy on docker hub
deploy:
    provider: script
    script:
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        docker push jecaro/hscalendar-server
