# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

services:
- docker

script:
# Create the docker image
- docker build -t hscalendar-server .
# Test the created image
- docker run hscalendar-server ./hscalendar-test

