copyright: 2019 Jean-Charles Quillet
maintainer: jeancharles.quillet@gmail.com
dependencies:
- ansi-terminal
- attoparsec
- base >= 4.7 && < 5
- brick
- esqueleto
- formatting
- hspec
- microlens-platform
- monad-loops
- monad-logger
- optparse-applicative
- persistent
- persistent-sqlite
- persistent-template
- rio
- transformers
- text-zipper
- text
- vty
- QuickCheck
name: hscalendar
version: 0.1.0.0
author: Jean-Charles Quillet
github: jecaro/haskell/hscalendar
license: BSD3

library:
  source-dirs: src

executables:
  hscalendar-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

tests:
  hscalendar-test:
    main: Spec.hs
    source-dirs: 
    - test 
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

default-extensions:
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
 
