copyright: 2019 Jean-Charles Quillet
maintainer: jeancharles.quillet@gmail.com
dependencies:
- QuickCheck
- aeson
- attoparsec
- base >= 4.7 && < 5
- bytestring
- case-insensitive
- containers
- cryptonite
- data-default
- directory
- either
- elm-syntax
- esqueleto
- formatting
- generics-sop
- haskell-to-elm
- hspec
- http-client
- http-client-tls
- http-media
- http-types
- microlens-platform
- monad-logger # Only needed for runNoLoggingT from Spec.hs
- mtl
- optparse-applicative
- path
- path-io
- persistent
- persistent-sqlite
- persistent-postgresql
- persistent-template
- prettyprinter
- quickcheck-instances
- refined
- rio
- rio-orphans
- servant
- servant-client
- servant-server
- temporary
- time
- unordered-containers
- wai-extra
- warp
- yaml
name: hscalendar
version: 0.1.0.0
author: Jean-Charles Quillet
github: jecaro/haskell/hscalendar
license: BSD3

library:
  source-dirs: src

executables:
  hscalendar-cli:
    source-dirs: cli
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar
  hscalendar-server:
    source-dirs: server
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar
  hscalendar-client:
    source-dirs: client
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar
  hscalendar-users:
    source-dirs: users
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar
  elm-generator:
    source-dirs: elm-generator
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

tests:
  hscalendar-test:
    main: Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

default-extensions:
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

