copyright: 2019 Jean-Charles Quillet
maintainer: jeancharles.quillet@gmail.com
dependencies:
- ansi-terminal
- attoparsec
- base >= 4.7 && < 5
- brick
- directory
- either
- esqueleto
- formatting
- hspec
- microlens-platform
- monad-logger
- monad-loops
- optparse-applicative
- path
- path-io
- persistent
- persistent-sqlite
- persistent-template
- QuickCheck
- quickcheck-instances
- refined
- rio
- rio-orphans
- template-haskell
- temporary
- text
- text-zipper
- transformers
- vty
- yaml
name: hscalendar
version: 0.1.0.0
author: Jean-Charles Quillet
github: jecaro/haskell/hscalendar
license: BSD3

library:
  source-dirs: src

executables:
  hscalendar-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

tests:
  hscalendar-test:
    main: Spec.hs
    source-dirs: 
    - test 
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - hscalendar

default-extensions:
  - DeriveGeneric
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - TypeSynonymInstances
 
