copyright: 2019 Jean-Charles Quillet
maintainer: jeancharles.quillet@gmail.com
dependencies:
- ansi-terminal
- attoparsec
- base >= 4.7 && < 5
- brick
- esqueleto
- microlens-platform
- monad-loops
- monad-logger
- mtl
- optparse-applicative
- persistent
- persistent-sqlite
- persistent-template
- safe
- safe-exceptions
- transformers
- time
- text
- text-zipper
- vty
name: hscalendar
version: 0.1.0.0
author: Jean-Charles Quillet
github: jecaro/haskell/hscalendar
license: BSD3
executables:
  hscalendar:
    source-dirs: ./
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
 